Nimi = input ("Kerro nimesi:")
print (f"Hei {Nimi}!")
Etunimi = input ("Kerro etunimesi:")
Sukunimi = input ("Kerro sukunimesi")
print (f"Hei {Etunimi}{Sukunimi}!")
Hedelmä = input ("Anna lempihedelmäsi:")
Hedelmä2 = input ("Anna toinenkin maistuva hedelmä")
print (f"Pidät hedelmistä {Hedelmä} ja {Hedelmä2}.")
Luku1 = int(input("Anna eka luku:"))
Luku2 = int(input("Anna toka luku:"))
print (f"Lukujen summa on {Luku1 + Luku2}.")
Desluku = float(input("Anna eka luku:"))
Desluku2 = float(input("Anna toka luku:"))
print (f"Lukujen summma on {Desluku + Desluku2}.")
Ukul = float(input("Anna eka luku:"))
Ukul2 = float(input("Anna toka luku:"))
print (f"{Ukul} jaettuna {Ukul2} on {Ukul/Ukul2}.")
Qwerty = int(input("Anna luku:"))
if Qwerty == 60:
    print ("Luku on 60")
else:
    print("Luku ei ole 60")