Lista = []
Sana1 = input("Anna Sana1")
Lista.append(Sana1)
Sana2 = input("Anna Sana2")
Lista.append(Sana2)
Sana3 = input("Anna Sana3")
Lista.append(Sana3)
Sana4 = input("Anna Sana4")
Lista.append(Sana4)
Sana5 = input("Anna Sana5")
Lista.append(Sana5)
Sana6 = input("Anna Sana6")
Lista.append(Sana6)
print("Pisin sana:")
print(max(Lista, key=len))
print("Lyhyin sana:")
print(min(Lista, key=len))
print("Eka sana:")
print(Lista[0])
print("Vika sana:")
print(Lista[-1])
print("Keskimmäisin sana:")
print(Lista[2])
